repos:
    - repo: local
      hooks:
          - id: update-pre-commit-hooks
            name: update pre-commit hooks
            entry: pre-commit autoupdate
            language: system
            pass_filenames: false
            types: [file]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
            args: ["--maxkb=2000"]
    - repo: local
      hooks:
          - id: lint
            name: Run linting
            entry: make lint
            language: system
            pass_filenames: false
