[package]
name = "zerv"
version = "0.0.0" # Use git tag
edition = "2024"
description = "Dynamic Versioning CLI"
license = "Apache-2.0"
repository = "https://github.com/wisarootl/zerv"

[[bin]]
name = "zerv"
path = "src/main.rs"

[dependencies]
chrono = ">=0.4.41"
clap = { version = ">=4.4", features = ["derive"] }

[dev-dependencies]
rstest = ">=0.18"
# TODO:
# Dummy comment to test cache - remove this line later
