[package]
name = "zerv"
version = "0.0.0" # Use git tag
edition = "2024"
description = "Dynamic Versioning CLI"
license = "Apache-2.0"
repository = "https://github.com/wisarootl/zerv"

[[bin]]
name = "zerv"
path = "src/main.rs"

[dependencies]
clap = { version = ">=4.4", features = ["derive"] }
