name: cd

on:
    push:
        branches:
            - main

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    versioning:
        name: versioning
        runs-on: ubuntu-latest
        outputs:
            new_release_version: ${{ steps.set-outputs.outputs.version }}
            new_release_published: ${{ steps.set-outputs.outputs.published }}
        steps:
            - name: Checkout
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  fetch-depth: 0

            - name: Check existing release
              id: check-release
              run: |
                  CURRENT_SHA=$(git rev-parse HEAD)
                  EXISTING_TAG=$(git tag --points-at $CURRENT_SHA | grep '^v' | head -1)
                  if [ -n "$EXISTING_TAG" ]; then
                      echo "existing_tag=$EXISTING_TAG" >> $GITHUB_OUTPUT
                      echo "existing_version=${EXISTING_TAG#v}" >> $GITHUB_OUTPUT
                      echo "has_existing=true" >> $GITHUB_OUTPUT
                  else
                      echo "has_existing=false" >> $GITHUB_OUTPUT
                  fi

            - id: release
              name: Release
              if: steps.check-release.outputs.has_existing == 'false'
              uses: cycjimmy/semantic-release-action@16ca923e6ccbb50770c415a0ccd43709a8c5f7a4 # v4.2.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set outputs
              id: set-outputs
              run: |
                  if [ "${{ steps.check-release.outputs.has_existing }}" == "true" ]; then
                      echo "version=${{ steps.check-release.outputs.existing_version }}" >> $GITHUB_OUTPUT
                      echo "published=true" >> $GITHUB_OUTPUT
                      echo "Using existing release: ${{ steps.check-release.outputs.existing_version }}"
                  else
                      echo "version=${{ steps.release.outputs.new_release_version }}" >> $GITHUB_OUTPUT
                      echo "published=${{ steps.release.outputs.new_release_published }}" >> $GITHUB_OUTPUT
                      echo "New release: ${{ steps.release.outputs.new_release_version }}"
                  fi

    release-bin:
        name: release-bin-github-${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        needs: versioning
        if: needs.versioning.outputs.new_release_published == 'true'
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: linux-x64
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      artifact_name: zerv
                      asset_name: zerv-linux-x86_64
                    - name: linux-arm64
                      os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                      artifact_name: zerv
                      asset_name: zerv-linux-arm64
                    - name: macos-x64
                      os: macos-latest
                      target: x86_64-apple-darwin
                      artifact_name: zerv
                      asset_name: zerv-macos-x86_64
                    - name: macos-arm64
                      os: macos-latest
                      target: aarch64-apple-darwin
                      artifact_name: zerv
                      asset_name: zerv-macos-arm64
                    - name: windows-x64
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                      artifact_name: zerv.exe
                      asset_name: zerv-windows-x86_64.exe
                    - name: windows-arm64
                      os: windows-latest
                      target: aarch64-pc-windows-msvc
                      artifact_name: zerv.exe
                      asset_name: zerv-windows-arm64.exe

        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # stable
              with:
                  toolchain: stable
                  targets: ${{ matrix.target }}

            - name: Install cross-compilation dependencies
              if: matrix.target == 'aarch64-unknown-linux-gnu'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y gcc-aarch64-linux-gnu
                  echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

            - name: Update Cargo.toml version
              run: |
                  echo "Updating version to ${{ needs.versioning.outputs.new_release_version }}"
                  if [[ "$RUNNER_OS" == "macOS" ]]; then
                      sed -i '' "s/^version = \".*\"/version = \"${{ needs.versioning.outputs.new_release_version }}\"/" Cargo.toml
                  else
                      sed -i "s/^version = \".*\"/version = \"${{ needs.versioning.outputs.new_release_version }}\"/" Cargo.toml
                  fi
              shell: bash

            - name: Build binary
              run: cargo build --release --target ${{ matrix.target }}

            - name: Upload binary to release
              uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13 # v2.11.2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
                  asset_name: ${{ matrix.asset_name }}
                  tag: v${{ needs.versioning.outputs.new_release_version }}
                  overwrite: true

    release-crates:
        name: release-crates
        runs-on: ubuntu-latest
        needs: [versioning, release-bin]
        if: needs.versioning.outputs.new_release_published == 'true'
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # stable
              with:
                  toolchain: stable

            - name: Update Cargo.toml version
              run: |
                  echo "Updating version to ${{ needs.versioning.outputs.new_release_version }}"
                  sed -i "s/^version = \".*\"/version = \"${{ needs.versioning.outputs.new_release_version }}\"/" Cargo.toml

            - name: Release to crates.io
              run: |
                  set -o pipefail
                  if cargo publish --token ${{ secrets.CARGO_TOKEN }} --allow-dirty 2>&1 | tee output.log; then
                      echo "Publish succeeded."
                  elif grep -q "already exists on crates.io index" output.log; then
                      echo "Version already exists, skipping publish."
                      exit 0
                  else
                      echo "Publish failed with unexpected error."
                      exit 1
                  fi
