name: CD

on:
    push:
        tags:
            - "v*"
    # release:
    #     # types: [published]
    #     types: [published, created, edited]
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # stable
              with:
                  toolchain: stable

            - name: Update version from tag
              run: |
                  TAG="${{ github.event.release.tag_name }}"
                  echo "Tag: $TAG"
                  sed -i "s/^version = \".*\"/version = \"${TAG#v}\"/" Cargo.toml

            - name: Publish to crates.io
              run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
