name: CD

on:
    push:
        branches:
            - main

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    versioning:
        name: Versioning
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.release.outputs.version }}
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  fetch-depth: 0

            - name: Release
              uses: cycjimmy/semantic-release-action@16ca923e6ccbb50770c415a0ccd43709a8c5f7a4 # v4.2.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Use version output
              run: echo "Released version is ${{ steps.release.outputs.version }}"

    publish:
        name: Publish
        runs-on: ubuntu-latest
        needs: versioning
        if: needs.versioning.outputs.version != ''
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # stable
              with:
                  toolchain: stable

            - name: Update Cargo.toml version
              run: |
                  echo "Updating version to ${{ needs.versioning.outputs.version }}"
                  sed -i "s/^version = \".*\"/version = \"${{ needs.versioning.outputs.version }}\"/" Cargo.toml

            - name: Publish to crates.io
              run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
