name: ci

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # stable
              with:
                  toolchain: stable

            - name: Restore cache
              uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                  key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
                  restore-keys: |
                      cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
                      cargo-${{ runner.os }}-

            - run: cargo install cargo-tarpaulin --locked || true

            - name: Debug Docker setup
              run: |
                  echo "=== Docker version ==="
                  docker --version
                  echo "=== Test working pattern from previous version ==="
                  mkdir -p /tmp/test-git-working
                  echo "test content" > /tmp/test-git-working/README.md
                  echo "=== Test alpine/git with entrypoint sh ==="
                  docker run --rm -v /tmp/test-git-working:/workspace -w /workspace --entrypoint sh alpine/git:latest -c "git init && git --git-dir=.git config user.name 'Test User' && git --git-dir=.git config user.email 'test@example.com' && git --git-dir=.git add . && git --git-dir=.git commit -m 'test'"
                  echo "=== Verify working pattern ==="
                  ls -la /tmp/test-git-working/
                  echo "=== Compare with current failing pattern ==="
                  mkdir -p /tmp/test-git-failing
                  echo "test content" > /tmp/test-git-failing/README.md
                  docker run --rm -v /tmp/test-git-failing:/workspace -w /workspace --user root alpine:latest sh -c "apk add --no-cache git && git init -b main && git config user.name 'Test' && git config user.email 'test@example.com' && git add . && git commit -m 'test'" || echo "FAILED as expected"
                  echo "=== Verify failing pattern ==="
                  ls -la /tmp/test-git-failing/

            - run: make test

            - name: Save cache
              uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
              if: always()
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                  key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@8c71dc039c2dd71d3821e89a2b58ecc7fee6ced9 # v5.3.0
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
              with:
                  fail_ci_if_error: true
                  token: ${{ secrets.CODECOV_TOKEN }}
                  verbose: true
