name: CI

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Setup Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
              with:
                  node-version: "latest"

            - name: Install Prettier
              run: npm install -g prettier

            - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd #v3.0.1
              with:
                  extra_args: --all-files

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: dtolnay/rust-toolchain@stable

            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                  key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

            - run: cargo install cargo-tarpaulin --locked || true

            - run: make test
