name: ci

on:
    pull_request:
        branches: [main]
        types: [opened, edited, synchronize, reopened]

permissions:
    pull-requests: read

jobs:
    semantic-pull-request:
        name: semantic-pull-request
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@fdd4d3ddf614fbcd8c29e4b106d3bbe0cb2c605d # v6.0.1
              name: Validate PR title
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
