name: ci

on:
    pull_request:
        branches: [main]
        types: [opened, edited, synchronize, reopened]

permissions:
    pull-requests: read

jobs:
    semantic-pull-request:
        name: semantic-pull-request
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
              name: Validate PR title
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
